language: python
python:

  - "2.7"

sudo: false

before_install:
  - apt-get install -y libwww-perl libgmp3-dev
  
# command to install dependencies

install: "pip install -r requirements.txt"

# command to run tests

script: python electron.py
